# Generated by Django 4.0.5 on 2022-06-26 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='number',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('activated', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='traj_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapi.number')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('secondname', models.CharField(max_length=30, null=True)),
                ('fathername', models.CharField(max_length=30, null=True)),
                ('dateofbirth', models.DateField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('profilepic', models.ImageField(null=True, upload_to='images/')),
                ('cardpic', models.ImageField(null=True, upload_to='images/')),
                ('car', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapi.number')),
            ],
        ),
        migrations.CreateModel(
            name='trajectories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('traj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapi.traj_ref')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('time', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapi.number')),
            ],
        ),
        migrations.CreateModel(
            name='pat_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(max_length=30, null=True)),
                ('startp_lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('startp_lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('endp_lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('endp_lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('cluster', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapi.number')),
            ],
        ),
        migrations.CreateModel(
            name='cluster_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('start_lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('end_lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('end_lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapi.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Type', models.CharField(max_length=30, null=True)),
                ('car_number', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapi.number')),
            ],
        ),
    ]
